name: Build WinForms App

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore TEXT.sln  # Замените MyApp.sln на имя вашего .sln файла

    - name: Build solution
      run: msbuild TEXT.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: List build output
      run: dir /s /b

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: winforms-exe
        path: '**/bin/Release/*.exe'
